// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 6.1
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_basic_linear(c,a,b){var d=jQuery;var f=d(this);var g=d("<div>").addClass("ws_effect").css({position:"absolute",display:"none","z-index":2,width:"200%",height:"100%",transform:"translate3d(0,0,0)"}).appendTo(b);function e(k,h,i,j){if(c.support.transform&&c.support.transition){if(h.right){h.left=-h.right;delete h.right}h.transform="translate3d("+h.left+"px,0,0)";delete h.left;h.transition="all "+i+"ms cubic-bezier(0.770, 0.000, 0.175, 1.000)";k.css(h);if(j){setTimeout(function(){k.css({transform:"",transition:""});j()},i)}}else{k.animate(h,{easing:"easeInOutExpo",duration:c.duration,complete:j?j:0})}}this.go=function(h,k){g.stop(1,1);var i=(!!((h-k+1)%a.length)^c.revers?"left":"right");d(a[k]).clone().css({position:"absolute",left:"auto",right:"auto",top:0,width:"50%"}).appendTo(g).css(i,0);d(a[h]).clone().css({position:"absolute",left:"auto",right:"auto",top:0,width:"50%"}).appendTo(g).css(i,"50%").show();g.css({left:"auto",right:"auto",top:0}).css(i,0).show();var j={};j[i]=-b.width();e(g,j,c.duration,function(){f.trigger("effectEnd");g.hide().html("")})}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 6.1
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"basic_linear",prev:"",next:"",duration:20*100,delay:20*100,width:1330,height:600,autoPlay:true,autoPlayVideo:false,playPause:true,stopOnHover:true,loop:false,bullets:true,caption:false,captionEffect:"slide",controls:true,onBeforeStep:0,images:0});